apiVersion: v1
kind: Job
metadata:
  name: parsing-job
  namespace: airflow
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: parsing-container
        image: tpomas/rag-pdf-base:minimal-0.0.2
        command: ["/bin/sh"]
        args: ["-c", "python3 /code/parsing.py --input /data --output /chunks --chunking_strategy by_title"]
        volumeMounts:
        - mountPath: /chunks
          name: chunks
        - mountPath: /data
          name: data
        - mountPath: /code
          name: code
      restartPolicy: Never
      volumes:
      - name: chunks 
        hostPath:
          path: <PATH_TO_CHUNKS> # input folder containing chunks from previous step
          type: Directory
      - name: data
        hostPath:
          path: <PATH_TO_DOCS> # input data folder
          type: Directory
      - name: code
        hostPath:
          path: <PATH_TO_CODE> # code folder
          type: Directory
